apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pacman-app
spec:
  destination:
    namespace: pacman-app
    server: https://kubernetes.default.svc
  project: default
  source:
    path: pacman-app/overlays/ocp4
    repoURL: https://github.com/rcarrata/rcs-apps
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true
  sync:
    comparedTo:
      destination:
        namespace: pacman
        server: https://kubernetes.default.svc
      source:
        path: pacman-app/overlays/ocp4
        repoURL: https://github.com/rcarrata/rcs-apps
        targetRevision: main
