apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookinfo-app
spec:
  destination:
    namespace: bookinfo-app
    server: https://kubernetes.default.svc
  project: default
  source:
    path: bookinfo-app/overlays/k8s
    repoURL: https://github.com/rcarrata/rcs-apps
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
