apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: products-app
spec:
  destination:
    namespace: products
    server: https://kubernetes.default.svc
  project: default
  source:
    path: products-app/overlays/dev
    repoURL: https://github.com/rcarrata/rcs-apps
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
